### ISSUE TITLE
The function named julian day should be renamed day of year

### ISSUE THREAD

**Issue by feigl** [csdms-contrib/slepian_oscar#2]
This function is incorrectly named.
It returns the day of year.
The Julian Day is defined by astronomers with respect to an origin time.
https://en.wikipedia.org/wiki/Julian_day#Julian_day_numbers

**Comment by fjsimons** [comment]
Thanks so much, Kurt. This erroneous nomenclature was held over from apocryphal practice. I believe I have corrected it in all of the `slepian-ABC` repositories. Glad you find them useful! I continue to write and revise, and my aim is to have everything 100% ship shape by the time I retire in 6756.

Some comments on the use of day-of-year and modified Julian Date in seismology 
James Edward Lawson, Jr.
Bulletin of the Seismological Society of America (1989) 79 (3): 921–923.
https://doi.org/10.1785/BSSA0790030921

**Comment by fjsimons** [comment]
Thanks so much, Kurt. This erroneous nomenclature was held over from apocryphal practice. I believe I have corrected it in all of the `slepian-ABC` repositories. Glad you find them useful! I continue to write and revise, and my aim is to have everything 100% ship shape by the time I retire in 6756.

_Some comments on the use of day-of-year and modified Julian Date in seismology_
James Edward Lawson, Jr.
**Bulletin of the Seismological Society of America** (1989) 79 (3): 921–923.
[10.1785/BSSA0790030921](https://doi.org/10.1785/BSSA0790030921)
